services:
  web:
    build: .
    container_name: flask_graphql_web
    command: >
      sh -c "
        flask run --host=0.0.0.0 --port=5000
      "
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=wsgi.py
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql+psycopg://postgres:postgres@db:5432/appdb
      - REDIS_URL=redis://redis:6379/0
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - SENDER_EMAIL=joinlovely@gmail.com
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ELASTICSEARCH_URL=${ELASTICSEARCH_URL}
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
      elasticsearch:
        condition: service_healthy
    volumes:
      - .:/app

  db:
    image: postgres:15
    container_name: flask_graphql_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  redis:
    image: redis:7
    container_name: flask_graphql_redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]

  celery:
    build: .
    container_name: flask_graphql_celery
    command: celery -A app.celery_app.celery worker --loglevel=info
    depends_on:
      - redis
      - db
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql+psycopg://postgres:postgres@db:5432/appdb
      - REDIS_URL=redis://redis:6379/0
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - SENDER_EMAIL=joinlovely@gmail.com

  
  celery-beat:
    build: .
    container_name: flask_graphql_celery_beat
    command: celery -A app.celery_app.celery beat --loglevel=info
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    container_name: es-secure
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
    volumes:
      - es-data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 20s
      timeout: 10s
      retries: 5
    
  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.0
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch


volumes:
  pgdata:
  es-data:
